### ISSUE TITLE
Potential `ChaChaBox` incompatibility

### ISSUE THREAD

**Issue by alexg-axis** [RustCrypto/nacl-compat#78]
Has anyone been able to validate that this works with libsodium? I can't get this package (crypto_box v0.8.2) to work with libsodium in C neither their Go secret box implementation.

From what I can tell, this implementation appends the AEAD tag[1,2] whilst libsodium [3] (and the libsodium author's Go implementation [4]) actually prepends the tag. Am I missing something?

[1] https://github.com/RustCrypto/traits/blob/44e9e1426b696306f7fe377afb852786f12ab5bc/aead/src/lib.rs#L388
[2] https://github.com/RustCrypto/traits/blob/44e9e1426b696306f7fe377afb852786f12ab5bc/aead/src/lib.rs#L283

[3] https://github.com/jedisct1/libsodium/blob/7ffd2a9057379f65f6ccfdbe0275dfa943fa5ea6/src/libsodium/crypto_box/curve25519xchacha20poly1305/box_curve25519xchacha20poly1305.c#LL160
[4] https://github.com/jedisct1/xsecretbox/blob/ebe41aef7befa74989e6cc22c1d4fd09affcb314/xsecretbox.go#L81

Test for producing a box in Rust:

```rust
use crypto_box::{aead::Aead, ChaChaBox, Nonce, PublicKey, SecretKey, KEY_SIZE};

#[test]
fn box_seal_integration_test() {
    // recipient's private key: 11eNS3ks54bUGiBR452k9p57Q2NomrtfRk1aH2GC5Pk=
    let recipient_public_key: [u8; KEY_SIZE] =
        base64::decode("8hPicHEf2A9xwSA0fNwCtZVIqc8SxEFccnnNTTXCRhs=")
            .expect("failed to decode sender public key")
            .try_into()
            .expect("failed to decode sender public key");

    // sender's public key: dJJaKruY/3ZzjTcZjZfj6Mkalg4/agMCKGG+Eq1A0XI=
    let sender_private_key: [u8; KEY_SIZE] =
        base64::decode("kOmH3ILWL/n34ltEikaSfdnmUNx7ajoNJqrxHzFNcPo=")
            .expect("failed to decode recipient private key")
            .try_into()
            .expect("failed");

    let plaintext = "Hello, World";

    let nonce_bytes =
        base64::decode("77RETs9bqUhbqPL6q8Ns+HWNj4x64weM").expect("failed to decode nonce");
    let nonce = Nonce::from_slice(&nonce_bytes);

    let boxed = ChaChaBox::new(
        &PublicKey::from(recipient_public_key),
        &SecretKey::from(sender_private_key),
    );
    let ciphertext_bytes = boxed
        .encrypt(nonce, plaintext.as_bytes())
        .expect("encryption failed");
    let ciphertext = base64::encode(ciphertext_bytes);

    assert_eq!("s1WCMPYEEYICFs+hSWuMyj0SD+lYGdSKQ2Pdcw==", ciphertext);
}
```

Test for decrypting it in Go.

```go
func TestDecryption(t *testing.T) {
	senderPublicKey, _ := base64.StdEncoding.DecodeString("dJJaKruY/3ZzjTcZjZfj6Mkalg4/agMCKGG+Eq1A0XI=")
	recipientPrivateKey, _ := base64.StdEncoding.DecodeString("11eNS3ks54bUGiBR452k9p57Q2NomrtfRk1aH2GC5Pk=")

	nonce, _ := base64.StdEncoding.DecodeString("77RETs9bqUhbqPL6q8Ns+HWNj4x64weM")
	ciphertext, _ := base64.StdEncoding.DecodeString("s1WCMPYEEYICFs+hSWuMyj0SD+lYGdSKQ2Pdcw==")

	var sk [32]byte
	copy(sk[:], recipientPrivateKey)

	var pk [32]byte
	copy(pk[:], senderPublicKey)

	key, err := xsecretbox.SharedKey(sk, pk)
	require.NoError(t, err)

	plaintext, err := xsecretbox.Open(nil, nonce, ciphertext, key[:])
	require.NoError(t, err)

	fmt.Printf("%s\n", plaintext)
}
```

**Comment by tarcieri** [comment]
I don’t think we ever did any compatibility testing for ChaCha.

It’s using the IETF construction where tags are generally appended rather than prepended.

In the next minor version we could conceivably try to change that, however it’s annoying that they would prepend tags with ChaCha.

XSalsa20 always uses prepended tags, though.

Since it initializes the AEAD interface you can use the detached API if you want to prepend the tag yourself.

**Comment by alexg-axis** [comment]
It's unclear to me whether or not the prepended tag is the only difference. It doesn't seem to work despite me prepending the tag. Any thoughts on what else could be clashing? I've double checked before that the shared key derived in the implementations match.

```rust
#[test]
fn box_seal_integration_test() {
    // recipient's private key: 11eNS3ks54bUGiBR452k9p57Q2NomrtfRk1aH2GC5Pk=
    let recipient_public_key: [u8; KEY_SIZE] =
        base64::decode("8hPicHEf2A9xwSA0fNwCtZVIqc8SxEFccnnNTTXCRhs=")
            .expect("failed to decode sender public key")
            .try_into()
            .expect("failed to decode sender public key");

    // sender's public key: dJJaKruY/3ZzjTcZjZfj6Mkalg4/agMCKGG+Eq1A0XI=
    let sender_private_key: [u8; KEY_SIZE] =
        base64::decode("kOmH3ILWL/n34ltEikaSfdnmUNx7ajoNJqrxHzFNcPo=")
            .expect("failed to decode recipient private key")
            .try_into()
            .expect("failed");

    let plaintext = "Hello, World";

    let nonce_bytes =
        base64::decode("77RETs9bqUhbqPL6q8Ns+HWNj4x64weM").expect("failed to decode nonce");
    let nonce = Nonce::from_slice(&nonce_bytes);

    let boxed = ChaChaBox::new(
        &PublicKey::from(recipient_public_key),
        &SecretKey::from(sender_private_key),
    );

    let mut ciphertext = vec![0; 16 + plaintext.len()];
    ciphertext.splice(16.., plaintext.as_bytes().iter().cloned());

    let tag = boxed
        .encrypt_in_place_detached(nonce, b"", &mut ciphertext[16..])
        .expect("encryption failed");

    ciphertext.splice(0..16, tag);

    let ciphertext = base64::encode(ciphertext);
    assert_eq!("SWuMyj0SD+lYGdSKQ2Pdc7NVgjD2BBGCAhbPoQ==", ciphertext);
}
```

```go
func TestDecryption(t *testing.T) {
	senderPublicKey, _ := base64.StdEncoding.DecodeString("dJJaKruY/3ZzjTcZjZfj6Mkalg4/agMCKGG+Eq1A0XI=")
	recipientPrivateKey, _ := base64.StdEncoding.DecodeString("11eNS3ks54bUGiBR452k9p57Q2NomrtfRk1aH2GC5Pk=")

	nonce, _ := base64.StdEncoding.DecodeString("77RETs9bqUhbqPL6q8Ns+HWNj4x64weM")
	ciphertext, _ := base64.StdEncoding.DecodeString("SWuMyj0SD+lYGdSKQ2Pdc7NVgjD2BBGCAhbPoQ==")

	var sk [32]byte
	copy(sk[:], recipientPrivateKey)

	var pk [32]byte
	copy(pk[:], senderPublicKey)

	key, err := xsecretbox.SharedKey(sk, pk)
	require.NoError(t, err)

	plaintext, err := xsecretbox.Open(nil, nonce, ciphertext, key[:])
	require.NoError(t, err)

	fmt.Printf("%s\n", plaintext)
}
```

I did assert, however, that the Go and C implementations are interoperable, however, which makes sense, given it's the same author and all.

**Comment by tarcieri** [comment]
The current tests for `ChaChaBox` are here:

https://github.com/RustCrypto/nacl-compat/blame/55c7854/crypto_box/tests/lib.rs#L165-L235

The test vectors are adapted from the PHP Sodium Compat test vectors here:

https://www.phpclasses.org/browse/file/122796.html

@alexg-axis it looks like the Go example you gave is still using Salsa instead of ChaCha as @trevyn pointed out earlier?

**Comment by alexg-axis** [comment]
The `xsecretbox` package  uses XChaCha (HChaCha20 and XChaCha20). 

Symmetric encryption: https://github.com/jedisct1/xsecretbox/blob/ebe41aef7befa74989e6cc22c1d4fd09affcb314/xsecretbox.go#L30

Key derivation: https://github.com/jedisct1/xsecretbox/blob/ebe41aef7befa74989e6cc22c1d4fd09affcb314/sharedkey.go#LL16

I'll look into the test vectors, thanks.

**Comment by alexg-axis** [comment]
I tried implementing a version that's compatible with the Rust library in Go to find what differs from libsodium and I identified the following differences:

1. libsodium prepends the tag
2. in libsodium, the first 32B of the message is encrypted with the second 32B chunk from the XChaCha20 output
3. the tag and cipher length are not authenticated in libsodium

To clarify on the second point. The implementation takes the first 64B of XChaCha20 and uses the first 32B as the poly1305 key, just like the Rust implementation, but it then uses the next 32B to XOR the first 32B of the message. I'm really unsure if I understood it correctly. I haven't read about a construction like that, it does smell a bit like they want to use all of the XChaCha20 key stream, but I don't know.

To me, it's clear that these packages likely won't work together right now.

**Comment by tarcieri** [comment]
`ChaChaBox` was added by @alxiong in https://github.com/RustCrypto/AEADs/pull/225

Looking at the test vectors again I'm not sure where they came from. The comment pointing to https://www.phpclasses.org/browse/file/122796.html seems unrelated.

The key derivation looks fine to me:

https://github.com/RustCrypto/nacl-compat/blob/55c7854/crypto_box/src/lib.rs#L410-L418

From what I can tell the problem is our `XChaCha20Poly1305` is the logical extension of `XChaCha20` to the IETF `ChaCha20Poly1305` AEAD construction, whereas that one looks more like the original `XSalsa20Poly1305`, which indeed uses a prepended tag and has no support for AAD.

That is very unfortunate, especially as one of the original design goals of `XChaCha20` was to be built on the IETF version of ChaCha20 from the start so as to avoid this sort of complexity explosion of "djb" vs IETF variants, and indeed the draft spec'd `AEAD_XChaCha20_Poly1305` this way: https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-xchacha-03#section-2

I guess we'll need to add another variant of XChaCha20Poly1305 to the `chacha20poly1305` crate, but for now, it can be implemented here.

cc @jedisct1 @paragonie-security

**Comment by tarcieri** [comment]
As a stopgap, we could vendor [`XSalsa20Poly1305`](https://docs.rs/xsalsa20poly1305/latest/xsalsa20poly1305/struct.XSalsa20Poly1305.html) from the `xsalsa20poly1305` crate, but made generic around the underlying stream cipher and renamed to e.g. `SecretBox`.

@jedisct1 can we count on `XChaCha20` following the spec from https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-xchacha-03#section-2 or do we need to implement HChaCha20 + djb-flavored ChaCha20?

**Comment by jedisct1** [comment]
This is the `secretbox` construction. You probably need to reimplement it, since it doesn't use the padding from the one designed for IETF protocols.

There's a [go implementation](https://github.com/jedisct1/xsecretbox) you can port.

**Comment by jedisct1** [comment]
But if you already have a `secretbox` implementation, you can just replace HSalsa with HChaCha, and Salsa with Chacha. Everything else is the same.

**Comment by tarcieri** [comment]
We have an implementation in the `xsalsa20poly1305` crate, but it’s specialized to XSalsa20.

We can probably copy-paste a generic implementation here and factor it out into its own crate eventually.

@jedisct1 it seems like we need to use [`ChaCha20Legacy`](https://docs.rs/chacha20/latest/chacha20/type.ChaCha20Legacy.html) with an additional up-front application of HChaCha20, rather than [`XChaCha20`](https://docs.rs/chacha20/latest/chacha20/type.XChaCha20.html) which follows @paragonie-security’s I-D (and is based on the IETF-flavored ChaCha20 with a 96-bit nonce)?

**Comment by jedisct1** [comment]
Yep, that sounds good.

**Comment by tarcieri** [comment]
I've done quite a bit of rewriting, converting the `xsalsa20poly1305` crate into a `crypto_secretbox` crate, which is now tested against libsodium-generated test vectors as of #111.

The `crypto_box` crate uses the `crypto_secretbox` crate as of #109, and I added libsodium-generated test vectors in #110.

@alexg-axis for some reason I couldn't get your test vectors to work. I tried in the commit history of #110.

Things seem to be working with libsodium-generated test vectors which are reproducible via the `test-vector-gen` crate in this repo, so I'm going to call this issue resolved.
